CREATE TABLE configs.app_config (
                                    id                       SMALLINT     PRIMARY KEY DEFAULT 1,
                                    min_teilnehmer           SMALLINT     NOT NULL DEFAULT 6,
                                    max_teilnehmer           SMALLINT     NOT NULL DEFAULT 22,
                                    anz_guests               SMALLINT     NOT NULL DEFAULT 4,
                                    algorithm_type           VARCHAR(20)  NOT NULL DEFAULT 'EXHAUSTIV',
                                    anz_team_generator       SMALLINT     NOT NULL DEFAULT 1,
                                    session_leerlauf_minuten SMALLINT     NOT NULL DEFAULT 15,
                                    session_maximal_stunden  SMALLINT     NOT NULL DEFAULT 1,
                                    halle_email              VARCHAR(120),
                                    halle_absage_vorlage     TEXT,
                                    halle_vorlauf_stunden    SMALLINT     NOT NULL DEFAULT 48,
                                    geaendert_von            SMALLINT,
                                    geaendert_am             TIMESTAMPTZ  NOT NULL DEFAULT now(),
                                    version                  BIGINT       NOT NULL DEFAULT 0,
                                    CONSTRAINT ck_app_config_singleton  CHECK (id = 1),
                                    CONSTRAINT ck_app_config_teilnehmer CHECK (min_teilnehmer > 0 AND max_teilnehmer >= min_teilnehmer),
                                    CONSTRAINT ck_app_config_guests     CHECK (anz_guests >= 0),
                                    CONSTRAINT ck_app_config_algo       CHECK (algorithm_type IN ('EXHAUSTIV', 'HEURISTIK')),
                                    CONSTRAINT ck_app_config_generator  CHECK (anz_team_generator >= 1),
                                    CONSTRAINT ck_app_config_session    CHECK (session_leerlauf_minuten > 0 AND session_maximal_stunden > 0),
                                    CONSTRAINT ck_app_config_vorlauf    CHECK (halle_vorlauf_stunden >= 0),
                                    CONSTRAINT fk_app_config_admin      FOREIGN KEY (geaendert_von) REFERENCES profil.admin_konto (id)
);